# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newentry_spray.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(612, 549)
        self.btn_showcal = QtGui.QPushButton(Dialog)
        self.btn_showcal.setGeometry(QtCore.QRect(270, 50, 31, 21))
        self.btn_showcal.setObjectName(_fromUtf8("btn_showcal"))
        self.cal_calendar = QtGui.QCalendarWidget(Dialog)
        self.cal_calendar.setGeometry(QtCore.QRect(150, 90, 280, 155))
        self.cal_calendar.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.cal_calendar.setObjectName(_fromUtf8("cal_calendar"))
        self.de_indate = QtGui.QDateEdit(Dialog)
        self.de_indate.setGeometry(QtCore.QRect(150, 50, 110, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI Semilight"))
        font.setBold(True)
        font.setWeight(75)
        self.de_indate.setFont(font)
        self.de_indate.setObjectName(_fromUtf8("de_indate"))
        self.lbl_showweek = QtGui.QLabel(Dialog)
        self.lbl_showweek.setGeometry(QtCore.QRect(50, 60, 81, 21))
        self.lbl_showweek.setText(_fromUtf8(""))
        self.lbl_showweek.setObjectName(_fromUtf8("lbl_showweek"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(80, 40, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI Semilight"))
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 300, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI Semilight"))
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(60, 260, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI Semilight"))
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(60, 340, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI Semilight"))
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 380, 121, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI Semilight"))
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 420, 121, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI Semilight"))
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.cb_type = QtGui.QComboBox(Dialog)
        self.cb_type.setGeometry(QtCore.QRect(150, 270, 221, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI Semilight"))
        font.setBold(True)
        font.setWeight(75)
        self.cb_type.setFont(font)
        self.cb_type.setObjectName(_fromUtf8("cb_type"))
        self.cb_type.addItem(_fromUtf8(""))
        self.cb_type.addItem(_fromUtf8(""))
        self.cb_type.addItem(_fromUtf8(""))
        self.lne_spraydesc = QtGui.QLineEdit(Dialog)
        self.lne_spraydesc.setGeometry(QtCore.QRect(150, 309, 221, 21))
        self.lne_spraydesc.setObjectName(_fromUtf8("lne_spraydesc"))
        self.lne_area = QtGui.QLineEdit(Dialog)
        self.lne_area.setGeometry(QtCore.QRect(150, 340, 71, 20))
        self.lne_area.setObjectName(_fromUtf8("lne_area"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(230, 340, 51, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI Semilight"))
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lne_spraydens = QtGui.QLineEdit(Dialog)
        self.lne_spraydens.setGeometry(QtCore.QRect(150, 380, 71, 20))
        self.lne_spraydens.setObjectName(_fromUtf8("lne_spraydens"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(230, 380, 101, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Segoe UI Semilight"))
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.te_comments = QtGui.QTextEdit(Dialog)
        self.te_comments.setGeometry(QtCore.QRect(150, 430, 221, 71))
        self.te_comments.setObjectName(_fromUtf8("te_comments"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.btn_showcal.setText(_translate("Dialog", "...", None))
        self.label.setText(_translate("Dialog", "Date: ", None))
        self.label_2.setText(_translate("Dialog", "Spray Description:", None))
        self.label_3.setText(_translate("Dialog", "Spray Type:", None))
        self.label_4.setText(_translate("Dialog", "Area Covered:", None))
        self.label_5.setText(_translate("Dialog", "Spray Density:", None))
        self.label_6.setText(_translate("Dialog", "Comments:", None))
        self.cb_type.setItemText(0, _translate("Dialog", "Fertiliser", None))
        self.cb_type.setItemText(1, _translate("Dialog", "Pesticide", None))
        self.cb_type.setItemText(2, _translate("Dialog", "Herbicide", None))
        self.label_7.setText(_translate("Dialog", "hectares", None))
        self.label_8.setText(_translate("Dialog", "Litres/hectare", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

