# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'report.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(643, 422)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 70, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.de_date = QtWidgets.QDateEdit(self.centralwidget)
        self.de_date.setGeometry(QtCore.QRect(150, 70, 110, 22))
        self.de_date.setObjectName("de_date")
        self.btn_showCal = QtWidgets.QPushButton(self.centralwidget)
        self.btn_showCal.setGeometry(QtCore.QRect(270, 70, 31, 23))
        self.btn_showCal.setObjectName("btn_showCal")
        self.calendar = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendar.setGeometry(QtCore.QRect(150, 100, 280, 155))
        self.calendar.setObjectName("calendar")
        self.lbl_header = QtWidgets.QLabel(self.centralwidget)
        self.lbl_header.setGeometry(QtCore.QRect(190, 20, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_header.setFont(font)
        self.lbl_header.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_header.setObjectName("lbl_header")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 180, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 210, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 240, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.lbl_fert = QtWidgets.QLabel(self.centralwidget)
        self.lbl_fert.setGeometry(QtCore.QRect(150, 180, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setBold(True)
        font.setWeight(75)
        self.lbl_fert.setFont(font)
        self.lbl_fert.setObjectName("lbl_fert")
        self.lbl_pest = QtWidgets.QLabel(self.centralwidget)
        self.lbl_pest.setGeometry(QtCore.QRect(150, 210, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setBold(True)
        font.setWeight(75)
        self.lbl_pest.setFont(font)
        self.lbl_pest.setObjectName("lbl_pest")
        self.lbl_herb = QtWidgets.QLabel(self.centralwidget)
        self.lbl_herb.setGeometry(QtCore.QRect(150, 240, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setBold(True)
        font.setWeight(75)
        self.lbl_herb.setFont(font)
        self.lbl_herb.setObjectName("lbl_herb")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 280, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.lbl_larea = QtWidgets.QLabel(self.centralwidget)
        self.lbl_larea.setGeometry(QtCore.QRect(150, 280, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setBold(True)
        font.setWeight(75)
        self.lbl_larea.setFont(font)
        self.lbl_larea.setObjectName("lbl_larea")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(80, 110, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(80, 140, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.lbl_startdate = QtWidgets.QLabel(self.centralwidget)
        self.lbl_startdate.setGeometry(QtCore.QRect(150, 110, 271, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setBold(True)
        font.setWeight(75)
        self.lbl_startdate.setFont(font)
        self.lbl_startdate.setText("")
        self.lbl_startdate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_startdate.setObjectName("lbl_startdate")
        self.lbl_enddate = QtWidgets.QLabel(self.centralwidget)
        self.lbl_enddate.setGeometry(QtCore.QRect(150, 140, 271, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setBold(True)
        font.setWeight(75)
        self.lbl_enddate.setFont(font)
        self.lbl_enddate.setText("")
        self.lbl_enddate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_enddate.setObjectName("lbl_enddate")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 643, 21))
        self.menubar.setObjectName("menubar")
        self.menuReport_Type = QtWidgets.QMenu(self.menubar)
        self.menuReport_Type.setObjectName("menuReport_Type")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAll_Season = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setBold(True)
        font.setWeight(75)
        self.actionAll_Season.setFont(font)
        self.actionAll_Season.setObjectName("actionAll_Season")
        self.actionMonthly = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setBold(True)
        font.setWeight(75)
        self.actionMonthly.setFont(font)
        self.actionMonthly.setObjectName("actionMonthly")
        self.actionWeekly = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setBold(True)
        font.setWeight(75)
        self.actionWeekly.setFont(font)
        self.actionWeekly.setObjectName("actionWeekly")
        self.menuReport_Type.addAction(self.actionAll_Season)
        self.menuReport_Type.addSeparator()
        self.menuReport_Type.addAction(self.actionWeekly)
        self.menubar.addAction(self.menuReport_Type.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Select Date:"))
        self.btn_showCal.setText(_translate("MainWindow", "..."))
        self.lbl_header.setText(_translate("MainWindow", "Season Report"))
        self.label_3.setText(_translate("MainWindow", "Fertiliser:"))
        self.label_4.setText(_translate("MainWindow", "Pesticide:"))
        self.label_5.setText(_translate("MainWindow", "Herbicide:"))
        self.lbl_fert.setText(_translate("MainWindow", "Litres"))
        self.lbl_pest.setText(_translate("MainWindow", "Litres"))
        self.lbl_herb.setText(_translate("MainWindow", "Litres"))
        self.label_10.setText(_translate("MainWindow", "Land Area Sprayed:"))
        self.lbl_larea.setText(_translate("MainWindow", "hectares"))
        self.label_11.setText(_translate("MainWindow", "Start Date:"))
        self.label_12.setText(_translate("MainWindow", "End Date:"))
        self.menuReport_Type.setTitle(_translate("MainWindow", "Report Type"))
        self.actionAll_Season.setText(_translate("MainWindow", "All Season"))
        self.actionMonthly.setText(_translate("MainWindow", "Monthly"))
        self.actionWeekly.setText(_translate("MainWindow", "Weekly"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

