# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spray_trackernew.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(980, 667)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(270, 540, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setBold(True)
        font.setWeight(75)
        self.btn_save.setFont(font)
        self.btn_save.setObjectName("btn_save")
        self.btn_showcal = QtWidgets.QPushButton(self.centralwidget)
        self.btn_showcal.setGeometry(QtCore.QRect(280, 50, 31, 21))
        self.btn_showcal.setObjectName("btn_showcal")
        self.de_indate = QtWidgets.QDateEdit(self.centralwidget)
        self.de_indate.setGeometry(QtCore.QRect(160, 50, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setBold(True)
        font.setWeight(75)
        self.de_indate.setFont(font)
        self.de_indate.setObjectName("de_indate")
        self.cal_calendar = QtWidgets.QCalendarWidget(self.centralwidget)
        self.cal_calendar.setGeometry(QtCore.QRect(50, 80, 280, 155))
        self.cal_calendar.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.cal_calendar.setObjectName("cal_calendar")
        self.btn_addEntry = QtWidgets.QPushButton(self.centralwidget)
        self.btn_addEntry.setGeometry(QtCore.QRect(50, 540, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setBold(True)
        font.setWeight(75)
        self.btn_addEntry.setFont(font)
        self.btn_addEntry.setObjectName("btn_addEntry")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 90, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lbl_showweek = QtWidgets.QLabel(self.centralwidget)
        self.lbl_showweek.setGeometry(QtCore.QRect(110, 90, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setBold(True)
        font.setWeight(75)
        self.lbl_showweek.setFont(font)
        self.lbl_showweek.setText("")
        self.lbl_showweek.setObjectName("lbl_showweek")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(50, 150, 821, 381))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(10)
        self.tableView.setFont(font)
        self.tableView.setStyleSheet("QTableView{\n"
"border : 0.5px solid gray;\n"
"border-radius : 25px;\n"
"}\n"
" QHeaderView::section:first {\n"
"     background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                       stop:0 #616161, stop: 0.5 #505050,\n"
"                                       stop: 0.6 #434343, stop:1 #656565);\n"
"     color: white;\n"
"     border: 1px solid #6c6c6c;\n"
"     border-radius : 25px;/*does not work*/\n"
"     padding-left: 4px;\n"
"     margin-left  : 25px;\n"
" }")
        self.tableView.setObjectName("tableView")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 110, 471, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setBold(True)
        font.setWeight(75)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lbl_start = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setBold(True)
        font.setWeight(75)
        self.lbl_start.setFont(font)
        self.lbl_start.setText("")
        self.lbl_start.setObjectName("lbl_start")
        self.horizontalLayout.addWidget(self.lbl_start)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lbl_stop = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setBold(True)
        font.setWeight(75)
        self.lbl_stop.setFont(font)
        self.lbl_stop.setText("")
        self.lbl_stop.setObjectName("lbl_stop")
        self.horizontalLayout.addWidget(self.lbl_stop)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 50, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btn_showAll = QtWidgets.QPushButton(self.centralwidget)
        self.btn_showAll.setGeometry(QtCore.QRect(160, 540, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setBold(True)
        font.setWeight(75)
        self.btn_showAll.setFont(font)
        self.btn_showAll.setObjectName("btn_showAll")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 980, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_save.setText(_translate("MainWindow", "SAVE"))
        self.btn_showcal.setText(_translate("MainWindow", "..."))
        self.btn_addEntry.setText(_translate("MainWindow", "ADD ENTRY"))
        self.label_2.setText(_translate("MainWindow", "Week:"))
        self.label.setText(_translate("MainWindow", "Start:"))
        self.label_3.setText(_translate("MainWindow", "Stop:"))
        self.label_4.setText(_translate("MainWindow", "Show by Week:"))
        self.btn_showAll.setText(_translate("MainWindow", "SHOW ALL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

